name: Build and Push Docker Images

on:
  push:
    paths:
      - 'ros2-docker-dev/Dockerfile'
      - 'R5.6-EM64T'
      - '.github/workflows/docker-image.yml'
      - 'vision/Dockerfile'
      - 'MinerU/Dockerfile'
      - 'mmr/Dockerfile'
      # 添加更多路径，根据你的目录结构调整

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: 
          # - 'ros2-docker-dev'
          # - 'vision'
          - 'mmr'
          # - 'R5.6-EM64T'
          # 添加更多目录，根据你的情况调整

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      # - name: Free Disk Space (Ubuntu)
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     # this might remove tools that are actually needed,
      #     # if set to "true" but frees about 6 GB
      #     tool-cache: false
          
      #     # all of these default to true, but feel free to set to
      #     # "false" if necessary for your workflow
      #     android: true
      #     dotnet: true
      #     haskell: true
      #     large-packages: true
      #     swap-storage: true

      # - name: Delete Unused 
      #   shell: bash
      #   run: |
      #     sudo rm -rf \
      #       "$AGENT_TOOLSDIRECTORY" \
      #       /opt/google/chrome \
      #       /opt/microsoft/msedge \
      #       /opt/microsoft/powershell \
      #       /opt/pipx \
      #       /usr/lib/mono \
      #       /usr/local/julia* \
      #       /usr/local/lib/android \
      #       /usr/local/lib/node_modules \
      #       /usr/local/share/chromium \
      #       /usr/local/share/powershell \
      #       /usr/share/dotnet \
      #       /usr/local/share/boost \
      #       /usr/share/swift
      #     df -h /

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.dir }}
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          file: ./${{ matrix.dir }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.dir }}--latest
            ghcr.io/${{ github.repository }}:${{ matrix.dir }}--${{ env.SHORT_SHA }}